version: "3.8"
services:
  jsonplaceholder:
    image: postgres:16
    container_name: postgres
    volumes:
      - jsonplaceholder_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jsonplaceholder_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    networks:
      - jsonplaceholder_network

  jsonplaceholder_app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_NAME: jsonplaceholder_data
      DB_USER: postgres
      DB_PASSWORD: 1234567890
    networks:
      - jsonplaceholder_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - jsonplaceholder
    networks:
      - jsonplaceholder_network

networks:
  jsonplaceholder_network:
    driver: bridge

volumes:
  jsonplaceholder_data:
