version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: jsonplaceholder_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dem

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - dem

  json_app:
    container_name: jsonplaceholder_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=jsonplaceholder_data
      - DB_USER=postgres
      - DB_PASSWORD=1234567890
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - dem
    command: ["python", "jsonplaceholder.py"]  # Comando para ejecutar el script Python

networks:
  dem:
    driver: bridge

volumes:
  postgres_data:
